<?/**@var $vkAccount Socnet\Entity\VkAccounts*/?>
<div>
    <div>
        <div>
            <div>
                <h3>Пользователи</h3>
            </div>
            <div>

                <a style="font-size: 20px;" href='<?=$addUrl?>' target='_top'>Импортировать новый кабинет ВК</a><br>

                <?php if (!empty($vkAccounts)) : ?>
                    <div class="CSSTableGenerator" >
                        <table >
                            <tr>
                               <!-- <td>Id</td>-->
                                <td>Имя</td>
                                <td>Что делать?</td>
                            </tr>
                            <? foreach($vkAccounts as $vkAccount): ?>
                                <? if (($vkAccount->getId() == 6 || $vkAccount->getId() == 11)
                                    && ($bidderUserId != 3
                                        && $bidderUserId != 5)
                                ): ?>
                                    <? continue; ?>
                                <? endif; ?>
                                <tr>
                                        <!--<td><?/*=$user->getId(); */?></td>-->
                                        <td><?=$vkAccount->getDescription() . ' - ' . $vkAccount->getName().' '.$vkAccount->getLastName(); ?></td>
                                        <td>
                                            <a href="<?= $this->url('clients', array('action'=>'cabinets', 'cabinet_id' => $vkAccount->getId()));?>">посмотреть рекламные кабинеты</a>
                                            <? if ($bidderUserId == 3): ?>
                                                |
                                            <a id="delete-link-<?=$vkAccount->getId()?>" style="color: red;" href="javascript: changeLinks(<?=$vkAccount->getId()?>)">удалить пользователя</a>
                                            <a class="h" id="confirm-delete-link-<?=$vkAccount->getId()?>" style="color: red;" href="<?= $this->url('vk', array('action'=>'accountDelete', 'vk_account_id' => $vkAccount->getId()));?>">подтверждаю удаление!</a>
                                            <? endif; ?>
                                        </td>
                                    </tr>
                            <? endforeach; ?>
                        </table>
                    </div>
                <? endif; ?>
            </div>
        </div>
    </div>
    <br><br> <b><big>Наша ссылка постбек:</big></b> <br> http://bidderonline.ru/socnet/postback/7c2ab528401522fad7c4e85e7ee3e3dc
    <br><b><big>Параметры:</big></b><br>subId=<b>сюда субайди</b><br> payment=<b>сюда бабло</b><br> leadId=<b>(необязательно) сюда уникальный ID лида</b>
    <br>
    <b><big>Пример:</big></b> <br>
    http://bidderonline.ru/socnet/postback/7c2ab528401522fad7c4e85e7ee3e3dc?subId=1233211&payment=100
</div>
<script>
    function changeLinks(id)
    {
        $('#delete-link-' + id + ', #confirm-delete-link-' + id).toggleClass('h');
        var selector = '#confirm-delete-link-' + id;
        $(selector).fadeOut('slow',function() {
            $(this).fadeIn('slow',function() {
            });
        });
    }
    $(function(){
        $('.navbar .nav li#home').addClass("active");
        $('.navbar .nav li#stat').removeClass("active");
    });
</script>