<? $campaignsIds = []; ?>
<div id="container">
    <div>
        <div>
            <div>
                <h3 style="display: inline-block;">Кампании</h3>
                <button type="button" id="campaigns_update_button" onclick="updateAllCampaigns();" class="btn btn-primary"> Обновить всё
                </button>
            </div>
            <div>
                <?php if (!empty($vkCampaigns)) : ?>
                    <div id="mainTable" class="CSSTableGenerator" >
                        <table class="process">
                            <tr class="process">
                                <td class="process">Название</td>
                                <td class="process">Статус</td>

                            </tr>
                            <? foreach($vkCampaigns as $campaign): ?>
                                <?/**@var $campaign Socnet\Entity\VkCampaigns*/?>
                                <? $campaignsIds[$campaign->getId()] = [$campaign->getStopFrom(), $campaign->getStopTo()];?>
                                <tr class="process">
                                    <td class="process <?=$campaign->getStatus() == 0 ? ' stopped' : ''?>">
                                        <div class="status-icon <?=$campaign->getStatus() == 1 ? ' play' : ' stop'?>"></div>
                                        <a href="<?= $this->url('socnet', array('action'=>'info','vk_account_id' => $vkAccountId, 'cabinet_id' => $cabinetId, 'client_id' => $campaign->getVkClientId(), 'campaign_id' => $campaign->getId()));?>" title="<?=$campaign->getName()?>"><?=mb_strlen($campaign->getName(), 'UTF-8') > 28 ? mb_substr($campaign->getName(), 0, 25, 'UTF-8').'...' : $campaign->getName();?></a>
                                        <div style="font-size: 8px; color: #808080;"><?=$campaign->getId()?></div>
                                        <div class="campaign-slider">
                                            <span style="float: left; margin-right: 8px;">Не активна c - по:</span>
                                            <div style="display: flex;" id="slider-range<?=$campaign->getId()?>"></div>
                                            <input type="text" disabled id="amount<?=$campaign->getId()?>" style="border:0; color:#020101; font-weight:bold; max-width: 78px; background: none;" />
                                        </div>
                                    </td>
                                    <td class="process"><?=$campaign->getStatus() == 0 ? 'остановлена' : ($campaign->getStatus() == 1 ? 'запущена' : 'удалена') ?></td>
                                </tr>
                            <? endforeach; ?>
                        </table>
                    </div>
                <? endif; ?>
            </div>
        </div>
    </div>
</div>

<?
$updateParams = [
    'action'=>'adsCheckerForce',
    'vk_account_id' => $vkAccountId,
    'cabinet_id' => $cabinetId
];
if (isset($vkClientId)) {
    $updateParams['client_id'] = (int) $vkClientId;
}
?>
<script type="text/javascript">
    function updateAllCampaigns() {
        $.blockUI({ css: {
            border: 'none',
            padding: '15px',
            backgroundColor: '#000',
            '-webkit-border-radius': '10px',
            '-moz-border-radius': '10px',
            opacity: .5,
            color: '#fff'
        } });

        $.post( '<?= $this->url('vk', $updateParams);?>', function( data ) {
            if (data == 1) {
                location.reload();
            }
        });
    }
    <? foreach ($campaignsIds as $id => $arCampaignInfo): ?>
    $("#slider-range<?=$id?>").slider({
        range: true,
        min: 0,
        max: 24,
        values: [ <?=$arCampaignInfo[0]?>, <?=$arCampaignInfo[1]?> ],
        slide: function( event, ui ) {
            if (ui.values[0] === ui.values[1]) {
                $( "#amount<?=$id?>" ).val('активна всегда');
            } else {
                $( "#amount<?=$id?>" ).val( ui.values[ 0 ] + " - " + ui.values[ 1 ] + ' час');
            }
        },
        stop: function(event, ui) {
            $.post( '<?= $this->url('saveSettings');?>', {params: {type: 'campaign', id: <?=$id?>, 'stop_from': ui.values[0], 'stop_to': ui.values[1]}}, function( data ) {

                if (data == 1) {
                    $.growlUI('Success', 'Кампания изменена.');
                } else {
                    $.growlUI('Блин!', data);
                }
            });
        }
    });
    var text = $( "#slider-range<?=$id?>" ).slider( "values", 0 ) == $( "#slider-range<?=$id?>" ).slider( "values", 1 ) ? 'активна всегда' : $( "#slider-range<?=$id?>" ).slider( "values", 0 ) +
        " - " + $( "#slider-range<?=$id?>" ).slider( "values", 1 ) + ' час';

    $( "#amount<?=$id?>" ).val(text);
    <? endforeach;?>

    $(function() {
        $( document ).tooltip();
    });

</script>

<style>
    label {
        display: inline-block;
        width: 5em;
    }
</style>