<div>
    <div>
        <div>
            <div>
                <h3>Клиенты</h3>
            </div>
            <div>
                <a style="font-size: 20px;" href='<?= $this->url('clients', array('action'=>'add'));?>' target='_top'>Добавить нового клиента</a>
                <?php if (!empty($users)) : ?>
                    <div class="CSSTableGenerator" >
                        <table class="process">
                            <tr class="process">
                                <td class="process">Id</td>
                                <td class="process">Имя</td>
                                <td class="process">Чё делать?</td>
                            </tr>
                            <? foreach($users as $user): ?>
                                <tr class="process">
                                    <td class="process"><?=$user->getId(); ?></td>
                                    <td class="process"><?=htmlspecialchars($user->getName()).' '.htmlspecialchars($user->getLastName()); ?><?=$user->getCompany() ? '('.htmlspecialchars($user->getCompany()).')' : ''?></td>
                                    <td class="process">
                                        <script src="//vk.com/js/api/openapi.js" type="text/javascript"></script>

                                        <div id="login_button" onclick="VK.Auth.login(authInfo);"></div>

                                        <script language="javascript">
                                            VK.init({
                                                apiId: <?=\Socnet\Controller\SocnetController::VK_APP_ID?>
                                            });
                                            function authInfo(response) {
                                                console.log(response);
                                            }
                                           // VK.Auth.getLoginStatus(authInfo);
                                            VK.Auth.login(authInfo, 32768+65536+2);
                                            VK.UI.button('login_button');
                                        </script>
                                        <div id="actions_link">
                                            <a href="<?= $this->url('clients', array('action'=>'cabinets'));?>">рекламные кабинеты</a>
                                        </div>

                                    </td>
                                </tr>
                            <? endforeach; ?>
                        </table>
                    </div>
                <? endif; ?>
            </div>
        </div>
    </div>
</div>