<form method="post" class="form-horizontal" role="form">
    <div>
        <h3>Клиенты</h3>
    </div>
    <div>
        <div class="CSSTableGenerator" >
            <table >
                <tr>
                    <td>Имя</td>
                    <td>Фамилия</td>
                    <td>Компания</td>
                </tr>
                <tr>
                    <td>
                        <div class="form-group">
                            <div class="col-sm-10">
                                <input class="form-control" name="name" id="focusedInput" type="text">
                            </div>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <div class="col-sm-10">
                                <input class="form-control" name="last_name" id="focusedInput1" type="text">
                            </div>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <div class="col-sm-10">
                                <input class="form-control" name="company" id="focusedInput2" type="text">
                            </div>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div id="submit-btn">
        <button type="submit" class="btn btn-primary">
            <i class="icon-user icon-white"></i> Сохранить
        </button>
    </div>
</form>
    