CREATE TABLE statsLogVk (
    ad_id INT UNSIGNED NOT NULL,
    ts INT UNSIGNED NOT NULL,
    price DECIMAL (8,2) UNSIGNED NOT NULL,
    impressions INT UNSIGNED NOT NULL,
    clicks INT UNSIGNED NOT NULL,
    spent DECIMAL (10,2) UNSIGNED NOT NULL,
    INDEX(ad_id),
    INDEX(ts)
) ENGINE=INNODB;