<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'StatsModule\Module'                        => __DIR__ . '/Module.php',
    'StatsModule\Controller\StatsController'    => __DIR__ . '/src/StatsModule/Controller/StatsController.php',
    'StatsModuleTest\Framework\TestCase'        => __DIR__ . '/tests/StatsModule/Framework/TestCase.php',
    'StatsModuleTest\SampleTest'                => __DIR__ . '/tests/StatsModule/SampleTest.php',
);